name: Sphinx Documentation

on:
  push:
    branches:    
      - master

jobs:
  build:


    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install documentation dependencies
      run: |
        pip install sphinx numpydoc matplotlib     
    - name: Install package
      run: |
        pip install -e .
    - name: Install Sphinx Latex
      run: |
        sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - name: Build documentation with sphinx
      run: |
        cd docs
        make clean
        make html
        make latexpdf
        cd ..
    - name: Deploy Docs
      run: |
        git clone https://github.com/cadop/seg1d.git --branch sphinx-docs --single-branch sphinx-docs
        cp -r docs/* sphinx-docs/
        cd sphinx-docs
        # touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.

    # runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@v2
    # # Standard drop-in approach that should work for most people.
    # - uses: cadop/seg1d@master
    #   with:
    #     docs-folder: "docs/"
    # # Example of using a custom build-command.
    # - uses: cadop/seg1d@master
    #   with:
    #     build-command: "sphinx-build -b html . _build"
    #     docs-folder: "docs2/"
    # # Grabbing custom dependencies and building as a pdf.
    # - uses: cadop/seg1d@master
    #   with:
    #     pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
    #     build-command: "make latexpdf"
    #     docs-folder: "docs2/"
    # # Great extra actions to compose with:
    # # Create an artifact of the html output.
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: DocumentationHTML
    #     path: docs/_build/html/
    # # Create an artifact out of the previously built pdf.
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: Documentation
    #     path: docs2/_build/latex/pdfexample.pdf
    # # Publish built docs to gh-pages branch.
    # # ===============================
    # - name: Commit documentation changes
    #   run: |
    #     git clone https://github.com/cadop/seg1d.git --branch sphinx-docs --single-branch sphinx-docs
    #     cp -r docs/_build/html/* sphinx-docs/
    #     cd sphinx-docs
    #     touch .nojekyll
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git commit -m "Update documentation" -a || true
    #     # The above command will fail if no changes were present, so we ignore
    #     # that.
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: sphinx-docs
    #     directory: sphinx-docs
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    # # ===============================

